# Generated by Django 3.1.13 on 2021-10-03 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_address_bankaccount_bitcoin_membershipstatus_notificationsetting_paymentaccount_privacy_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermembership',
            name='membership_type',
            field=models.CharField(choices=[('free', 'free'), ('premium', 'premium')], default='free', max_length=20),
        ),
        migrations.DeleteModel(
            name='MembershipStatus',
        ),
    ]
